# Generated by Django 4.0.4 on 2022-05-16 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registro',
            new_name='Registros',
        ),
    ]
