# Generated by Django 4.0.4 on 2022-05-17 18:41

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_rename_registro_registros'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registros',
            options={'verbose_name_plural': 'Registros'},
        ),
        migrations.AlterField(
            model_name='registros',
            name='importe',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
